server:
  port: ${PORT:8080}

spring:
  r2dbc:
    url: r2dbc:pool:postgresql://aws-0-us-west-1.pooler.supabase.com:5432/postgres
    username: postgres.tuuxndxyhvjrnvqkgrma
    password: UpfA3yGIo7CFFLyK

  # Propiedades personalizadas - DEBEN estar en el nivel raíz
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/prs2-83d22
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com




